[package]
name = "year-25-day-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0"
aoc_lib = { path = "../../aoc_lib" }
